# Generated by Django 4.0.5 on 2022-07-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customseed',
            name='biome_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
