import {ref} from "vue";

const selected_version = ref(19);

const minecraft_biomes = [
  "ocean",
  "plains",
  "desert",
  "windswept hills",
  "forest",
  "taiga",
  "swamp",
  "river",
  "nether wastes",
  "the end",
  "frozen ocean",
  "frozen river",
  "snowy plains",
  "snowy mountains",
  "mushroom fields",
  "mushroom field shore",
  "beach",
  "desert hills",
  "wooded hills",
  "taiga hills",
  "mountain edge",
  "jungle",
  "jungle hills",
  "sparse jungle",
  "deep ocean",
  "stony shore",
  "snowy beach",
  "birch forest",
  "birch forest hills",
  "dark forest",
  "snowy taiga",
  "snowy taiga hills",
  "old growth pine taiga",
  "giant tree taiga hills",
  "windswept forest",
  "savanna",
  "savanna plateau",
  "badlands",
  "wooded badlands",
  "badlands plateau",
  "small end islands",
  "end midlands",
  "end highlands",
  "end barrens",
  "warm ocean",
  "lukewarm ocean",
  "cold ocean",
  "deep warm ocean",
  "deep lukewarm ocean",
  "deep cold ocean",
  "deep frozen ocean",  //50
  "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
  "the void",
  "",
  "sunflower plains",   // 129
  "desert lakes",
  "windswept gravelly hills",
  "flower forest",
  "taiga mountains",
  "swamp hills",
  "", "", "", "", "",
  "ice spikes",
  "", "", "", "", "", "", "", "",
  "modified jungle",
  "",
  "modified jungle edge",
  "", "", "",
  "old growth birch forest",
  "tall birch hills",
  "dark forest hills",
  "snowy taiga mountains",
  "",
  "old growth spruce taiga",
  "giant spruce taiga hills",
  "modified gravelly mountains",
  "windswept savanna",
  "shattered savanna plateau",
  "eroded badlands",
  "modified wooded badlands plateau",
  "modified badlands plateau" ,
  "bamboo jungle" ,
  "bamboo jungle hills",
  "soul sand valley" ,
  "crimson forest" ,
  "warped forest"  ,
  "basalt deltas",
  "dripstone caves",
  "lush caves",
  "",
  "meadow",
  "grove" ,
  "snowy slopes",
  "jagged peaks",
  "frozen peaks",
  "stony peaks",
  "deep dark",
  "mangrove swamp"
];


const versions = {
  19: "1.19",
  18: "1.18",
}

selected_version.value = process.server ? 19 : window.localStorage.getItem('version') || 19


export {
  selected_version,
  versions,
  minecraft_biomes
}